services:
  postgres:
    image: postgres:16
    container_name: ticket_support_postgres
    environment:
      POSTGRES_DB: ticket_support
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_password
    ports:
      - "5432:5432"
    volumes:
      - ticket_support_pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ticket_support_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  ticket_support_pgdata:
